server:
  port: 8181

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db
    username: root
    password: root
  
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka

ISSUER_URI: http://localhost:8181/auth/realms/lesytruong
